name: Build and Deploy UTM Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Build site
        env:
          WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          mkdir -p dist
          cp index.html dist/
          cp styles.css dist/ || true
          sed -i "s|YOUR_WEBHOOK_URL|$WEBHOOK_URL|g" dist/index.html
          sed -i "s|YOUR_WEBHOOK_SECRET|$WEBHOOK_SECRET|g" dist/index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
